#excessoes
try:
    print(2/0)
except:
    print("Aconteceu algum erro")
    